name = "supabaseWork"          # 项目名称
type = "module"             # 设置为 "module" 以支持 ES 模块

[env.production]
main = "worker.js"  # Worker 的入口点
account_id = "e48fcd2bb249444a99a3f6a46549c604"  # 填写你的 Cloudflare 账户 ID
workers_dev = true          # 启用开发模式
compatibility_flags = []    # 可选：设置兼容性标志

[build]
command = "npm install"     # 构建命令
